# -*- coding: utf-8 -*-
"""run_in_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    Candidate's Google Drive
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/gdrive')
# %cd /content/gdrive/MyDrive/part-ii-metaphor-detector/src/

!pip install transformers

import torch
torch.cuda.get_device_name(0)

!python3 /content/gdrive/MyDrive/part-ii-metaphor-detector/src/main.py --experiment_number "12" --model_indices 0